# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Destiny Lore - TLDR
email: leftathome@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The story of Destiny is spread across a lot of places - item flavor text,
  quest or bounty steps, grimoire cards, in-game voiceover dialogue and even
  a few fully animated cinematics.  We try to boil all that down for you.
baseurl: "/destiny-lore-tldr" # the subpath of your site, e.g. /blog
url: "http://leftathome.github.io" # the base hostname & protocol for your site
twitter_username: leftathome
github_username:  leftathome
collections:
  entries:
    foo: bar
    defaults:
      - scope:
          path: ""
          type: entries
        values:
          layout: page

# Build settings
markdown: kramdown
#theme: minima

exclude: [vendor]
